version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data

  go-movie-api:
    image: go-movie-api:latest
    # build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

volumes:
  db-data:
  redis-data: